/* Formatted on 12/9/2023 5:52:15 PM (QP5 v5.388) */
SELECT PPNF.FIRST_NAME, PPNF.LAST_NAME, PPNF.FULL_NAME
  FROM PER_PERSON_NAMES_F PPNF, PER_ALL_PEOPLE_F PAPF
 WHERE     TRUNC (SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE
                               AND PAPF.EFFECTIVE_END_DATE
       AND TRUNC (SYSDATE) BETWEEN PPNF.EFFECTIVE_START_DATE
                               AND PPNF.EFFECTIVE_END_DATE
       AND PAPF.PERSON_ID = PPNF.PERSON_ID
       AND PPNF.NAME_TYPE = 'GLOBAL'