/* Formatted on 12/9/2023 10:20:27 PM (QP5 v5.388) */
SELECT HAPTL.NAME     AS POSITION
  FROM HR_ALL_POSITIONS_F     HAPF,
       HR_ALL_POSITIONS_F_TL  HAPTL,
       PER_ALL_ASSIGNMENTS_M  PAAM,
       PER_ALL_PEOPLE_F       PAPF
 WHERE     TRUNC (SYSDATE) BETWEEN HAPF.EFFECTIVE_START_DATE
                               AND HAPF.EFFECTIVE_END_DATE
       AND TRUNC (SYSDATE) BETWEEN HAPTL.EFFECTIVE_START_DATE
                               AND HAPTL.EFFECTIVE_END_DATE
       AND TRUNC (SYSDATE) BETWEEN PAAM.EFFECTIVE_START_DATE
                               AND PAAM.EFFECTIVE_END_DATE
       AND TRUNC (SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE
                               AND PAPF.EFFECTIVE_END_DATE
       AND HAPF.POSITION_ID = HAPTL.POSITION_ID
       AND PAAM.PERSON_ID = PAPF.PERSON_ID
       AND PAAM.POSITION_ID = HAPF.POSITION_ID
       AND HAPTL.LANGUAGE = 'US'