/* Formatted on 1/2/2024 9:57:46 AM (QP5 v5.388) */
SELECT PPN.DISPLAY_NAME        AS FULLNAME,
       PPOS.DATE_START     AS START_DATE,
       HAPTL.NAME          AS POSITION,
       HOUFL.NAME          AS DEPARTMAN,
       PJFL.NAME           AS JOB,
       PAPF.PERSON_NUMBER  AS PERNR
  FROM PER_ALL_PEOPLE_F               PAPF,
       PER_ALL_ASSIGNMENTS_M          PAAM,
       PER_PERSON_NAMES_F             PPN,
       HR_ALL_POSITIONS_F             HAPF,
       HR_ALL_POSITIONS_F_TL          HAPTL,
       PER_JOBS_F                     PJF,
       PER_JOBS_F_TL                  PJFL,
       HR_ORGANIZATION_UNITS          HOU,
       HR_ORG_UNIT_CLASSIFICATIONS_F  HOUCF,
       HR_ORGANIZATION_UNITS_F_TL     HOUFL,
       (SELECT *
          FROM PER_PERIODS_OF_SERVICE Z
         WHERE     Z.PRIMARY_FLAG = 'Y'
               AND Z.PERIOD_OF_SERVICE_ID =
                   (SELECT MAX (X.PERIOD_OF_SERVICE_ID)
                     FROM PER_PERIODS_OF_SERVICE X
                    WHERE X.PRIMARY_FLAG = 'Y' AND Z.PERSON_ID = X.PERSON_ID))
       PPOS
 WHERE     TRUNC (SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE
                               AND PAPF.EFFECTIVE_END_DATE
       AND PAPF.PERSON_ID = PPN.PERSON_ID
       AND PAPF.PERSON_ID = PAAM.PERSON_ID
       AND PAAM.POSITION_ID = HAPF.POSITION_ID
       AND PAAM.JOB_ID = PJF.JOB_ID
       AND PAAM.ORGANIZATION_ID = HOU.ORGANIZATION_ID
       AND PAAM.PERIOD_OF_SERVICE_ID = PPOS.PERIOD_OF_SERVICE_ID
       AND PAAM.ASSIGNMENT_STATUS_TYPE = 'ACTIVE'
       AND PAAM.PRIMARY_FLAG = 'Y'
       AND PAAM.ASSIGNMENT_TYPE IN ('E', 'C')
       AND TRUNC (SYSDATE) BETWEEN PAAM.EFFECTIVE_START_DATE
                               AND PAAM.EFFECTIVE_END_DATE
       AND PPN.NAME_TYPE = 'GLOBAL'
       AND TRUNC (SYSDATE) BETWEEN PPN.EFFECTIVE_START_DATE
                               AND PPN.EFFECTIVE_END_DATE
       AND PJF.JOB_ID = PJFL.JOB_ID
       AND PJFL.LANGUAGE = 'US'
       AND HAPF.POSITION_ID = HAPTL.POSITION_ID
       AND TRUNC (SYSDATE) BETWEEN HAPF.EFFECTIVE_START_DATE
                               AND HAPF.EFFECTIVE_END_DATE
       AND TRUNC (SYSDATE) BETWEEN HAPTL.EFFECTIVE_START_DATE
                               AND HAPTL.EFFECTIVE_END_DATE
       AND HAPTL.LANGUAGE = 'US'
       AND HOUCF.ORGANIZATION_ID = HOU.ORGANIZATION_ID
       AND HOUCF.ORGANIZATION_ID = HOUFL.ORGANIZATION_ID
       AND TRUNC (SYSDATE) BETWEEN HOUCF.EFFECTIVE_START_DATE
                               AND HOUCF.EFFECTIVE_END_DATE
       AND TRUNC (SYSDATE) BETWEEN HOUFL.EFFECTIVE_START_DATE
                               AND HOUFL.EFFECTIVE_END_DATE
       AND HOUFL.LANGUAGE = 'US'
       AND HOUCF.CLASSIFICATION_CODE = 'DEPARTMENT'
       ORDER BY PAPF.PERSON_NUMBER ASC